# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('having_IP_Address', models.IntegerField()),
                ('URL_Length', models.IntegerField()),
                ('Shortining_Service', models.IntegerField()),
                ('having_At_Symbol', models.IntegerField()),
                ('double_slash_redirecting', models.IntegerField()),
                ('Prefix_Suffix', models.IntegerField()),
                ('having_Sub_Domain', models.IntegerField()),
                ('SSLfinal_State', models.IntegerField()),
                ('Domain_registeration_length', models.IntegerField()),
                ('Favicon', models.IntegerField()),
                ('port', models.IntegerField()),
                ('HTTPS_token', models.IntegerField()),
                ('Request_URL', models.IntegerField()),
                ('URL_of_Anchor', models.IntegerField()),
                ('Links_in_tags', models.IntegerField()),
                ('SFH', models.IntegerField()),
                ('Submitting_to_email', models.IntegerField()),
                ('Abnormal_URL', models.IntegerField()),
                ('Redirect', models.IntegerField()),
                ('on_mouseover', models.IntegerField()),
                ('RightClick', models.IntegerField()),
                ('popUpWidnow', models.IntegerField()),
                ('Iframe', models.IntegerField()),
                ('age_of_domain', models.IntegerField()),
                ('DNSRecord', models.IntegerField()),
                ('web_traffic', models.IntegerField()),
                ('Page_Rank', models.IntegerField()),
                ('Google_Index', models.IntegerField()),
                ('Links_pointing_to_page', models.IntegerField()),
                ('Statistical_report', models.IntegerField()),
                ('Result', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='URLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='datamodel',
            name='theURL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phish_inspec.URLModel'),
        ),
    ]
