# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish_inspec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='url',
            field=models.URLField(max_length=150),
        ),
    ]
